# stage 1: build api server binary
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
WORKDIR /app/cmd/api
RUN GOOS=linux GOARCH=arm64 go build -o /api

# stage 2: create a minimal image to run api server
FROM alpine:latest
# install bash
RUN apk add --no-cache bash curl
WORKDIR /app
# install scripts dependencies
COPY scripts/wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it
# copy the api binary
COPY --from=builder /api .
COPY .env .
# use wait-for-it to wait for postgres to be ready before starting the api server
CMD ["sh", "-c", "wait-for-it postgres:5432 -- ./api"]
