# stage 1: build the Go application
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
WORKDIR /app/cmd/server
RUN GOOS=linux GOARCH=arm64 go build -o /server

# stage 2: create a minimal image to run the application
FROM alpine:latest
WORKDIR /app
COPY --from=builder /server .
COPY .env .
CMD ["./server"]
