// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/metrics.proto

package grpcserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *GetMetricsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMetricsByHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsByHostRequest) Reset() {
	*x = GetMetricsByHostRequest{}
	mi := &file_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsByHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsByHostRequest) ProtoMessage() {}

func (x *GetMetricsByHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsByHostRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsByHostRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetricsByHostRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetMetricsByHostRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformVer   string                 `protobuf:"bytes,4,opt,name=platform_ver,json=platformVer,proto3" json:"platform_ver,omitempty"`
	KernelVer     string                 `protobuf:"bytes,5,opt,name=kernel_ver,json=kernelVer,proto3" json:"kernel_ver,omitempty"`
	Uptime        int64                  `protobuf:"varint,6,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Cpu           float64                `protobuf:"fixed64,7,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Ram           float64                `protobuf:"fixed64,8,opt,name=ram,proto3" json:"ram,omitempty"`
	Disk          string                 `protobuf:"bytes,9,opt,name=disk,proto3" json:"disk,omitempty"`
	Network       string                 `protobuf:"bytes,10,opt,name=network,proto3" json:"network,omitempty"`
	Time          string                 `protobuf:"bytes,11,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *Metric) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Metric) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Metric) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Metric) GetPlatformVer() string {
	if x != nil {
		return x.PlatformVer
	}
	return ""
}

func (x *Metric) GetKernelVer() string {
	if x != nil {
		return x.KernelVer
	}
	return ""
}

func (x *Metric) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *Metric) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Metric) GetRam() float64 {
	if x != nil {
		return x.Ram
	}
	return 0
}

func (x *Metric) GetDisk() string {
	if x != nil {
		return x.Disk
	}
	return ""
}

func (x *Metric) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Metric) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_proto_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *GetMetricsResponse) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_proto_metrics_proto protoreflect.FileDescriptor

const file_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"\x13proto/metrics.proto\x12\n" +
	"monitoring\")\n" +
	"\x11GetMetricsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"K\n" +
	"\x17GetMetricsByHostRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x90\x02\n" +
	"\x06Metric\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12!\n" +
	"\fplatform_ver\x18\x04 \x01(\tR\vplatformVer\x12\x1d\n" +
	"\n" +
	"kernel_ver\x18\x05 \x01(\tR\tkernelVer\x12\x16\n" +
	"\x06uptime\x18\x06 \x01(\x03R\x06uptime\x12\x10\n" +
	"\x03cpu\x18\a \x01(\x01R\x03cpu\x12\x10\n" +
	"\x03ram\x18\b \x01(\x01R\x03ram\x12\x12\n" +
	"\x04disk\x18\t \x01(\tR\x04disk\x12\x18\n" +
	"\anetwork\x18\n" +
	" \x01(\tR\anetwork\x12\x12\n" +
	"\x04time\x18\v \x01(\tR\x04time\"B\n" +
	"\x12GetMetricsResponse\x12,\n" +
	"\ametrics\x18\x01 \x03(\v2\x12.monitoring.MetricR\ametrics2\xbc\x01\n" +
	"\x0eMetricsService\x12Q\n" +
	"\x10GetLatestMetrics\x12\x1d.monitoring.GetMetricsRequest\x1a\x1e.monitoring.GetMetricsResponse\x12W\n" +
	"\x10GetMetricsByHost\x12#.monitoring.GetMetricsByHostRequest\x1a\x1e.monitoring.GetMetricsResponseB\x1cZ\x1a./internal/grpc;grpcserverb\x06proto3"

var (
	file_proto_metrics_proto_rawDescOnce sync.Once
	file_proto_metrics_proto_rawDescData []byte
)

func file_proto_metrics_proto_rawDescGZIP() []byte {
	file_proto_metrics_proto_rawDescOnce.Do(func() {
		file_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)))
	})
	return file_proto_metrics_proto_rawDescData
}

var file_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_metrics_proto_goTypes = []any{
	(*GetMetricsRequest)(nil),       // 0: monitoring.GetMetricsRequest
	(*GetMetricsByHostRequest)(nil), // 1: monitoring.GetMetricsByHostRequest
	(*Metric)(nil),                  // 2: monitoring.Metric
	(*GetMetricsResponse)(nil),      // 3: monitoring.GetMetricsResponse
}
var file_proto_metrics_proto_depIdxs = []int32{
	2, // 0: monitoring.GetMetricsResponse.metrics:type_name -> monitoring.Metric
	0, // 1: monitoring.MetricsService.GetLatestMetrics:input_type -> monitoring.GetMetricsRequest
	1, // 2: monitoring.MetricsService.GetMetricsByHost:input_type -> monitoring.GetMetricsByHostRequest
	3, // 3: monitoring.MetricsService.GetLatestMetrics:output_type -> monitoring.GetMetricsResponse
	3, // 4: monitoring.MetricsService.GetMetricsByHost:output_type -> monitoring.GetMetricsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_metrics_proto_init() }
func file_proto_metrics_proto_init() {
	if File_proto_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metrics_proto_goTypes,
		DependencyIndexes: file_proto_metrics_proto_depIdxs,
		MessageInfos:      file_proto_metrics_proto_msgTypes,
	}.Build()
	File_proto_metrics_proto = out.File
	file_proto_metrics_proto_goTypes = nil
	file_proto_metrics_proto_depIdxs = nil
}
